### PR TITLE
Styles!

### PR DESCRIPTION
**Pull request by TaylorWilton**
With this PR I do a few things:

1. Fix the bootstrap syntax (not everything needs a row class)
2. Change the project to use SCSS as a preprocessor, and with that add gulp as a temporary build system for compiling and minifying the css (I'm eagerly awaiting @WillMoreland's webpack system)
3.  Improve the layout of the app, and begin the de-bootstrapification process.

Part of this process involved making bootstrap part of the project again, so that I could include it in the build files (I have effectively made a custom build by commenting out the cruft). While I know this goes against an earlier PR, I feel that the change is justified. 

Also, this comic is now applicable, since the css compiles
image

### CODE REVIEW

**Comment by un1r8okq** [comment]
@TaylorDeakin this is waaaaaaay to big of a PR. Do you really expect us to read through 96 files with 9k additions and 251 deletions? Either
1. Make a smaller working PR with the smallest slice of working changes as possible
2. Merge a smaller PR that breaks things to a feature branch

Either way PRs should be ~10 files with only a few hundred lines of code changed.

I tired to do shit like this at Xero and my PRs just got immediately closed for being too big 😄

**Comment by TaylorDeakin** [comment]
most of that is bootstrap

**Comment by un1r8okq** [comment]
Looks like most of the `build` directory is generated... maybe .gitignore it?

**Comment by TaylorWilton** [comment]
You're looking at it the wrong way - `styles.css` is the generated file. The `build` directory contains the source files that compile to it. This includes bootstrap's source files, which make up the majority of this PR. 

However, I'm going to resubmit this PR with a few changes.

**Pull request closed without merging**
